apiVersion: gke.cattle.io/v1
kind: GKEClusterConfig
metadata:
  name: example-autopilot-cluster
spec:
  clusterName: "example-autopilot-cluster"
  description: "Example cluster with autopilot"
  labels: {}
  region: "us-east1"
  projectID: "example-project"
  kubernetesVersion: "1.27.3-gke.100"
  loggingService: ""
  monitoringService: ""
  enableKubernetesAlpha: false
  clusterIpv4Cidr: "10.43.0.0/16"
  ipAllocationPolicy:
    useIpAliases: true
  clusterAddons:
    httpLoadBalancing: true
    networkPolicyConfig: false
    horizontalPodAutoscaling: true
  networkPolicyEnabled: false
  network: default
  subnetwork: default
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: false
  masterAuthorizedNetworks:
    enabled: false
  locations: []
  maintenanceWindow: ""
  googleCredentialSecret: "cattle-global-data:cc-gqpl4"
  autopilotConfig:
    enabled: true
